export enum DoctorSpecialty {
  AllergyImmunology = 'ALLERGY & IMMUNOLOGY',
  Anesthesiology = 'ANESTHESIOLOGY',
  Cardiology = 'CARDIOLOGY',
  Dermatology = 'DERMATOLOGY',
  EmergencyMedicine = 'EMERGENCY MEDICINE',
  Endocrinology = 'ENDOCRINOLOGY',
  FamilyMedicine = 'FAMILY MEDICINE',
  Gastroenterology = 'GASTROENTEROLOGY',
  GeneralSurgery = 'GENERAL SURGERY',
  HematologyOncology = 'HEMATOLOGY-ONCOLOGY',
  InfectiousDisease = 'INFECTIOUS DISEASE',
  InternalMedicine = 'INTERNAL MEDICINE',
  Nephrology = 'NEPHROLOGY',
  Neurology = 'NEUROLOGY',
  ObstetricsGynecology = 'OBSTETRICS & GYNECOLOGY',
  Ophthalmology = 'OPHTHALMOLOGY',
  OrthopedicSurgery = 'ORTHOPEDIC SURGERY',
  Otolaryngology = 'OTOLARYNGOLOGY',
  Pediatrics = 'PEDIATRICS',
  PhysicalMedicineRehabilitation = 'PHYSICAL MEDICINE & REHABILITATION',
  Psychiatry = 'PSYCHIATRY',
  Pulmonology = 'PULMONOLOGY',
  Radiology = 'RADIOLOGY',
  Rheumatology = 'RHEUMATOLOGY',
  Urology = 'UROLOGY',
}
