export enum DoctorSpecialty {
  ALLERGY_IMMUNOLOGY = 'Allergy & Immunology',
  ANESTHESIOLOGY = 'Anesthesiology',
  CARDIOLOGY = 'Cardiology',
  DERMATOLOGY = 'Dermatology',
  EMERGENCY_MEDICINE = 'Emergency Medicine',
  ENDOCRINOLOGY = 'Endocrinology',
  FAMILY_MEDICINE = 'Family Medicine',
  GASTROENTEROLOGY = 'Gastroenterology',
  GENERAL_SURGERY = 'General Surgery',
  HEMATOLOGY_ONCOLOGY = 'Hematology-Oncology',
  INFECTIOUS_DISEASE = 'Infectious Disease',
  INTERNAL_MEDICINE = 'Internal Medicine',
  NEPHROLOGY = 'Nephrology',
  NEUROLOGY = 'Neurology',
  OBSTETRICS_GYNECOLOGY = 'Obstetrics & Gynecology',
  OPHTHALMOLOGY = 'Ophthalmology',
  ORTHOPEDIC_SURGERY = 'Orthopedic Surgery',
  OTOLARYNGOLOGY = 'Otolaryngology',
  PEDIATRICS = 'Pediatrics',
  PHYSICAL_MEDICINE_REHABILITATION = 'Physical Medicine & Rehabilitation',
  PSYCHIATRY = 'Psychiatry',
  PULMONOLOGY = 'Pulmonology',
  RADIOLOGY = 'Radiology',
  RHEUMATOLOGY = 'Rheumatology',
  UROLOGY = 'Urology',
}
